import { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { Button, Card, Input, Spacer, Loading, Textarea } from '@geist-ui/core'
import GeneratedImage from '../components/GeneratedImage'
import { useState } from 'react'
import { Settings } from '@geist-ui/icons'

type PageState = {
  prompt: string | null
  imageId: string | null
  status: 'idle' | 'loading' | 'done'
}

const Home: NextPage = () => {
  const [pageState, setPageState] = useState({
    prompt: null,
    imageId: null,
    status: 'idle'
  } as PageState)

  console.log(pageState)

  async function submitPrompt () {
    const response = await fetch('/api/images', {
      method: 'POST',
      body: JSON.stringify({
        prompt: pageState.prompt
      })
    })
    const data = await response.json()
    console.log({ data })
    setPageState({
      ...pageState,
      imageId: data.id
    })
  }
  const clearState = () => {
    setPageState({
      prompt: null,
      imageId: null,
      status: 'idle'
    } as PageState)
  }
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.main}>
        <div>
          <Card shadow>
            <div
              style={{
                display: 'flex',
                minHeight: '300px',
                width: '300px',
                flexDirection: 'column',
                justifyContent: 'space-between'
              }}
            >
              {/* <div
              style={{
                display: 'flex',
                alignItems: 'center',
                justifyContent: 'space-between'
              }}
            >
              <p>hoverable card</p>
              <Settings size={16} />
            </div> */}
              <div>
                {pageState.imageId ? (
                  <div
                    style={{
                      width: '300px',
                      height: '250px'
                    }}
                  >
                    <GeneratedImage imageId={pageState.imageId} />
                  </div>
                ) : (
                  <Textarea
                    style={{
                      width: '300px',
                      height: '250px'
                    }}
                    onChange={e => {
                      setPageState({
                        ...pageState,
                        prompt: e.target.value
                      })
                    }}
                    onKeyDown={e => {
                      if (e.key === 'Enter') {
                        setPageState({
                          ...pageState,
                          imageId: null
                        })
                        submitPrompt()
                      }
                    }}
                    placeholder='my awesome idea...'
                  />
                )}
              </div>
              {pageState.imageId ? (
                <Button onClick={clearState} auto scale={0.5} type='secondary'>
                  New
                </Button>
              ) : (
                <Button auto scale={0.5} type='secondary'>
                  ✨ Create
                </Button>
              )}
            </div>
          </Card>
          <Spacer h={0.5} />
        </div>
      </main>
    </div>
  )
}

export default Home
