import { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { Input, Spacer, Loading, Textarea } from '@geist-ui/core'
import GeneratedImage from '../components/GeneratedImage'
import { useState } from 'react'

type PageState = {
  prompt: string | null
  imageId: string | null
  status: 'idle' | 'loading' | 'done'
}

const Home: NextPage = () => {
  const [pageState, setPageState] = useState({
    prompt: null,
    imageId: null,
    status: 'idle'
  } as PageState)

  console.log(pageState)

  async function submitPrompt () {
    const response = await fetch('/api/images', {
      method: 'POST',
      body: JSON.stringify({
        prompt: pageState.prompt
      })
    })
    const data = await response.json()
    console.log({ data })
    setPageState({
      ...pageState,
      imageId: data.id
    })
  }
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.main}>
        <div>
          <Textarea
            onChange={e => {
              setPageState({
                ...pageState,
                prompt: e.target.value
              })
            }}
            onKeyDown={e => {
              if (e.key === 'Enter') {
                setPageState({
                  ...pageState,
                  imageId: null
                })
                submitPrompt()
              }
            }}
            placeholder='my awesome idea'
          />{' '}
          <Spacer h={0.5} />
        </div>
        {pageState.imageId && <GeneratedImage imageId={pageState.imageId} />}
      </main>
    </div>
  )
}

export default Home
